ktor:
  environment: dev
  application:
    modules:
      - com.colin.ApplicationKt.module
  deployment:
    port: 8080


jwt:
  realm: Authentication
  subject: Authentication
  issuer: "http://0.0.0.0:8080"
  sign: "**x6g3F92c#*_"
