package generator.domain.entity

import org.ktorm.database.Database
import org.ktorm.entity.Entity
import org.ktorm.entity.sequenceOf
import org.ktorm.schema.*
    
    

/**
* generated by KtormGenerator
* @date 2023-11-02
*/
interface City : Entity<City> {
    companion object : Entity.Factory<City>()
    var iD: Int
    var name: String
    var countryCode: String
    var district: String
    var population: Int
}

object Citys : Table<City>("city") {
    val iD = int("ID").primaryKey().bindTo { it.iD }
    val name = varchar("Name").bindTo { it.name }
    val countryCode = varchar("CountryCode").bindTo { it.countryCode }
    val district = varchar("District").bindTo { it.district }
    val population = int("Population").bindTo { it.population }
}



val Database._citys get() = this.sequenceOf(Citys)
